// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwbevytqwvrksygeixil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YmV2eXRxd3Zya3N5Z2VpeGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Njk4ODEsImV4cCI6MjA2NjM0NTg4MX0.F7d_3S_VWrd_sC3tHGFy_hME_ufOlrioqeOaBJ82mb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});